In [21]:
# Задание 1
# Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет
# array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

import numpy as np

N = 10

nparr = np.arange(0, N)
fleppednparr = np.flip(nparr)

fleppednparr

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [30]:
# Задание 2
# Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

diagfleppednparr = np.diag(fleppednparr)
np.sum(np.diagonal(diagfleppednparr))

45

In [35]:
# Задание 3
# Решите систему уравнений:
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

from numpy import linalg

a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [93]:
# Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя.
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
# Остальные столбцы - количество покупок категорий товаров этим пользователем:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

import matplotlib.pyplot as plt

bestmatchuserid = 0

for useridminusone, user_for_check in enumerate(users_stats):
    next_user_stats = np.array([0, 1, 2, 0, 0, 0])

#     ax = plt.axes() # этот блок рисует график сопоставления кривых
#     plt.xlim([0, 5])
#     plt.ylim([0, 5])
#     plt.plot(next_user_stats)
#     plt.plot(user_for_check)
#     plt.show()

    # расчёт длин кривых и индекса их косинусного сходства
    currentcosindex = np.dot(next_user_stats, user_for_check) / (np.linalg.norm(next_user_stats) * np.linalg.norm(user_for_check))
#     print(useridminusone + 1, currentcosindex)
    if currentcosindex > bestmatch:
        bestmatchuserid = useridminusone + 1 # +1 потому что по условию задачи в таблице юзеры
                                             # нумеруются с еденицы, а не с нуля

print(f'Самый похожий юзер с ID {bestmatchuserid}')

Самый похожий юзер с ID 8
